# Generated by Django 5.2.7 on 2025-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_saletransaction_cashier_product_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Tax percentage (e.g., 12 for 12%)', max_digits=5),
        ),
    ]
